import manifest from './screenshots.json';

export type Device = 'iphone' | 'ipad' | 'appletv' | 'watch' | 'mac';

export interface ScreenshotItem {
  id: string;
  device: Device;
  locale: string;
  slug: string;
  alt: string;
  caption?: string;
  theme?: 'light' | 'dark';
  order: number;
  width: number;
  height: number;
  webp: string;
  jpg: string;
  capturedAt: string;
  source: string;
}

const items = manifest.items as ScreenshotItem[];

/**
 * Screenshots for a given device, sorted by manifest order. Defaults to the
 * en-US locale. Generated by scripts/import-screenshots.mjs — see
 * README.md "Screenshots".
 */
export function screenshots(device: Device, opts?: { locale?: string }): ScreenshotItem[] {
  const locale = opts?.locale ?? 'en-US';
  return items
    .filter((item) => item.device === device && item.locale === locale)
    .sort((a, b) => a.order - b.order);
}

/** A single screenshot by its manifest id, e.g. "ipad/arcade". */
export function screenshotById(id: string): ScreenshotItem | undefined {
  return items.find((item) => item.id === id);
}
